version: '3.9'
services:
    wordpress:
        image: wordpress:6.3.1-php8.0-fpm
        networks:
            - wordpress
        depends_on:
            - db
        volumes:
            - type: bind
              source: ./public
              target: /var/www/html
            - ./.php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_NAME=exampledb
            - WORDPRESS_DB_USER=exampleuser
            - WORDPRESS_DB_PASSWORD=examplepass

    db:
        image: mariadb:10.5
        networks:
            - wordpress
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=exampledb
            - MYSQL_USER=exampleuser
            - MYSQL_PASSWORD=examplepass
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./.db:/var/lib/mysql
        command:
            - '--default-authentication-plugin=mysql_native_password'

    nginx:
        image: nginx:1
        networks:
            - wordpress
        depends_on:
            - wordpress
        ports:
            - '80:80' # http

        volumes:
            - type: bind
              source: ./public
              target: /var/www/html
            - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
    wordpress:
        name: wp-wordpress
        driver: bridge
